# The URL the site will be built for
base_url = "./"
compile_sass = true
title = "Vaibhav Jhawar"
description = "I blog about tech, science, math, etc."
generate_feeds = false
generate_sitemap = false
generate_robots_txt = false

theme = "hyde"

[extra]
hyde_sticky = false
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    { url = "https://linkedin.com/in/vaibhav-jhawar/", name = "LinkedIn" },
    { url = "https://github.com/vaibhavjhawar/", name = "Github" },
    { url = "https://vaibhavjhawar.gitlab.io/blog/", name = "Creative Blog" },
]
